Event post for Lunch with Microsoft
wics-uw/website pull request #262
Opened 2016-09-24 19:04 UTC by shivangipatwardhan2018

Please let me know if anything is to be changed.

2016-09-24 19:12 UTC, arshiamufti commented on content/F2016/F16-Lunch-with-Microsoft.md
> +
- software engineer, program manager, etc should be all lowercase
- this is a nitpicky thing but I'm not sure that values should be separated by semi-colons. "Ankita Dey (software engineer), Kyle Oline (program manager on Windows Internet of Things)...."

2016-09-24 19:14 UTC, arshiamufti commented on content/F2016/F16-Lunch-with-Microsoft.md
> ++ **When:** Tuesday, 12:30&ndash;1:30PM
include the date: Tuesday, September 27

2016-09-24 19:16 UTC, arshiamufti commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Come join Microsoft for lunch and meet current full-times!
"current full time engineers" would be better

2016-09-24 19:16 UTC, arshiamufti commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30-1:30pm to join us for Taco Farm.
`&ndash;` instead of the dash

2016-09-25 02:01 UTC, arshiamufti commented on content/F2016/F16-Lunch-with-Microsoft.md
> +
update: I was wrong about the semicolons. http://www.bristol.ac.uk/arts/exercises/grammar/grammar_tutorial/page_05.htm @shivangipatwardhan2018 pointed this out.

2016-09-25 02:07 UTC, shivangipatwardhan2018 commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Come join Microsoft for lunch and meet current full-times!
Yes you are right. Fixed it :)

2016-09-25 02:08 UTC, arshiamufti commented on content/F2016/F16-Lunch-with-Microsoft.md
> ++ **When:** Tuesday, 12:30&ndash;1:30PM
(I noticed the tea party event didn't have that but most of our past event posts do and it's clearer to include the date anyway)

2016-09-25 19:00 UTC, fboxwala commented
Nice work - could you just squash your commits into one commit, and next time make sure you're working off of your own feature branch and not master?

(in case you need it -  [guide to squash](https://github.com/wics-uw/git-workshop-W16/wiki/Squashing-Commits))

2016-09-25 22:25 UTC, shivangipatwardhan2018 commented
Yes will do.

2016-09-28 05:17 UTC, arshiamufti commented
So....this wasn't merged in before the event.

2016-09-28 13:43 UTC, evykassirer commented
@shivangipatwardhan2018 can you make the changes people asked for so we can merge it?

2016-09-28 14:07 UTC, shivangipatwardhan2018 commented
I did a while back I am not aware there was anything else to change.

On Wed, Sep 28, 2016 at 9:43 AM, Evy Kassirer <notifications@github.com>
wrote:

> @shivangipatwardhan2018 <https://github.com/shivangipatwardhan2018> can
> you make the changes people asked for so we can merge it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/wics-uw/website/pull/262#issuecomment-250170185>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AHM88iGtFgjsW8tdnWnRZ9NIxEuENITlks5qum8AgaJpZM4KFuCk>
> .
>

2016-09-28 14:11 UTC, evykassirer requested changes
you included the review, but I don't see the ndash or the squashed commit. maybe you changed it but didn't push? sorry for the confusion!

2016-09-28 14:11 UTC, evykassirer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30-1:30pm to join us for Taco Farm.
ndash here too?

2016-09-28 14:13 UTC, fboxwala commented
@shivangipatwardhan2018 Oh sorry, I was waiting for you to squash the commits before I merged, and I guess we didn't touch base fast enough. Sorry about the confusion

2016-09-28 14:18 UTC, shivangipatwardhan2018 commented
okay I was not aware. I will do it after work today

2016-09-28 14:22 UTC, evykassirer commented
one cool thing is that we can do squash and merge now when we merge pull requests

so that means you could actually just not squash them and I can do it for you when I merge

<img width="322" alt="screen shot 2016-09-28 at 10 21 26 am" src="https://cloud.githubusercontent.com/assets/5634097/18917271/5e2fcfde-8565-11e6-97fb-81ef87279679.png">

You're welcome to try squashing on your own anyways if you want, and I think adding the ndash would be good too.

2016-09-28 22:17 UTC, shivangipatwardhan2018 commented
Evy you were right the push had not gone though fixed the ndash issue also all should be okay now. :)

2016-09-28 22:25 UTC, evykassirer commented
oh haha so you did it but just didn't push - classic 😄

2016-09-28 22:26 UTC, evykassirer requested changes

2016-09-28 22:26 UTC, evykassirer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30&ndash;1:30pm to join us for Taco Farm.
oh one more thing - lines should only be 80 characters long
when you do a new line it won't actually do a line break on the website, it just makes the file cleaner and easier to read (this is common for coding too)

2016-09-28 22:26 UTC, evykassirer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +We will be joined by Antika Dey, Software Engineer in Product Ads; Kyle Olive, Program Manager on Windows Internet of Things; Sage Franch, Tech Evagelist and founder and TrendyTechie.ca.
here too

2016-09-29 13:56 UTC, annalorimer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30&ndash;1:30pm to join us for Taco Farm.
I customized my text editor to newline at 80 characters and I haven't seen any issues?

2016-09-29 14:08 UTC, evykassirer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30&ndash;1:30pm to join us for Taco Farm.
this isn't your PR though? am confuse
this line is 102 characters long and line 11 is longer

2016-09-29 14:10 UTC, annalorimer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30&ndash;1:30pm to join us for Taco Farm.
Oh I meant that I'm confused about "when you do a new line it won't actually do a line break"

2016-09-29 14:11 UTC, evykassirer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30&ndash;1:30pm to join us for Taco Farm.
oh, yeah I explained that poorly
I wanted to say that new lines in the code doesn't mean line breaks when it shows up on the website

2016-09-29 14:12 UTC, annalorimer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30&ndash;1:30pm to join us for Taco Farm.
Can't @shivangipatwardhan2018 just newline after 80 chars to get the correct line lengths?

2016-09-29 14:14 UTC, evykassirer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30&ndash;1:30pm to join us for Taco Farm.
yeah exactly - there should be newline after every 80 chars

but that doesn't mean that on the website every line will cut off after 80 characters

2016-09-29 14:15 UTC, annalorimer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30&ndash;1:30pm to join us for Taco Farm.
Ah ok we're saying the same thing. @shivangipatwardhan2018 does this make sense?

2016-09-29 14:16 UTC, evykassirer commented on content/F2016/F16-Lunch-with-Microsoft.md
> +Got class in-between? No worries, drop by anytime between 12:30&ndash;1:30pm to join us for Taco Farm.
yeah I was just trying to give context hehe

2016-09-29 18:57 UTC, evykassirer commented
👌 👌 👌 👌 👌 👌 👌 👌

2016-09-29 18:57 UTC, evykassirer approved these changes

2016-09-29 18:57 UTC, merged