added tshirt post
wics-uw/website pull request #299
Opened 2017-01-31 00:36 UTC by mokaixu

2017-02-08 14:16 UTC, annalorimer requested changes

2017-02-08 14:16 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> +Date: 2017-02-05
This date will need to be changed so that this post shows up as the top post.

2017-02-08 14:16 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> +Slug: options-panel-w17
This slug is wrong. Should be t-shirt related.

2017-02-08 14:16 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> ++  Be appropriate and adhere to the UW and WiCS codes of conduct
This needs to be updated so that the information is consistent with the poster. So we need to add the rule about omitting gendered-symbols etc.

2017-02-08 14:16 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> +Deadline is February 5! Submit to wics-ugrad@lists.uwaterloo.ca
Deadline needs to be updated.

2017-02-08 14:16 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> ++ **Who:** Women in the Faculty of Math
We need to specify that this is women only as well.

2017-02-08 16:30 UTC, evykassirer commented on content/W2017/W17-tshirt-contest.md
> +Love fashion?
if you want line breaks, you need an empty line between the lines. if you don't, you can just put this all on the same line

2017-02-08 16:30 UTC, evykassirer commented on content/W2017/W17-tshirt-contest.md
> +the WiCS T-Shirt Contest... you could be the next trendsetter!
(same here)

2017-02-08 16:30 UTC, evykassirer commented on content/W2017/W17-tshirt-contest.md
> ++ **Who:** Women and Non-Binary students in the Faculty of Math
this list isn't working hmm

try using `-` instead of `+`

2017-02-08 16:30 UTC, evykassirer commented on content/W2017/W17-tshirt-contest.md
> ++ **Who:** Women and Non-Binary students in the Faculty of Math
https://wics-site-pr-299.herokuapp.com/

2017-02-08 16:36 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> ++ **Who:** Women and Non-Binary students in the Faculty of Math
This list renders fine for me, the one listing the rules doesn't though.

2017-02-08 16:37 UTC, evykassirer commented on content/W2017/W17-tshirt-contest.md
> ++ **Who:** Women and Non-Binary students in the Faculty of Math
oops my bad

okay the problem is that you need a new line before the list starts

2017-02-08 16:38 UTC, annalorimer requested changes

2017-02-08 16:38 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> ++ **Who:** Women and Non-Binary students in the Faculty of Math
I think the issue may be that there's two spaces between the '+' and the text.

2017-02-08 16:39 UTC, evykassirer commented on content/W2017/W17-tshirt-contest.md
> ++ **Who:** Women and Non-Binary students in the Faculty of Math
nah I think two spaces is okay ^_^

markdown is so confusing lol

2017-02-11 03:54 UTC, mokaixu reviewed
How are these changes?

2017-02-11 05:47 UTC, fat1996 requested changes
Could we maybe underline or create a hyperlink for the email address?

2017-02-11 17:41 UTC, annalorimer requested changes

2017-02-11 17:41 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> ++  **Who:** Women and Non-Binary students in the Faculty of Math
Link to the FAQ

2017-02-11 17:41 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
>  +  To be inclusive of women and non-binary individuals, designs
"To be" -> "Must be"

2017-02-11 17:41 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
>  +  Be appropriate and adhere to the UW and WiCS codes of conduct
"UW" -> University of Waterloo and link to our code of conduct

2017-02-11 17:41 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> +Deadline is February 26! Submit files to wics-ugrad@lists.uwaterloo.ca
what time is the deadline?

2017-02-12 05:22 UTC, mokaixu reviewed
Added the changes :D

2017-02-12 06:37 UTC, fat1996 requested changes
Codes-of-conduct->Code-of-conduct

2017-02-13 14:43 UTC, annalorimer requested changes
Looks great other than the one typo!

2017-02-13 14:43 UTC, annalorimer commented on content/W2017/W17-tshirt-contest.md
> ++  Be appropriate and adhere to the University of Waterloo and WiCS [codes-of-conduct]({filename}/pages/code-of-conduct.md)
codes-of-conduct -> code-of-conduct

2017-02-15 18:20 UTC, annalorimer commented
@mokaixu Can you make these changes please? It'd be nice if this was the top post on the site for a while before the ctf event goes up.

2017-02-16 04:13 UTC, mokaixu reviewed
changed code of conduct typo

2017-02-16 04:13 UTC, mokaixu commented
sorry for the alteness i hope this is good

2017-02-16 04:28 UTC, fat1996 requested changes
There's an extra '+' on the 'who' line.

2017-02-18 06:33 UTC, fat1996 commented
@mokaixu Could you please make the requested changes at your earliest convenience? I wanna close this PR.

2017-02-19 13:17 UTC, mokaixu reviewed
Took out the extra plus

2017-02-19 14:24 UTC, annalorimer approved these changes

2017-02-19 14:24 UTC, merged