changed volunteer link
wics-uw/website pull request #300
Opened 2017-01-31 02:51 UTC by mokaixu

2017-01-31 02:53 UTC, evykassirer commented on content/pages/volunteers.md
> +form](https://lists.uwaterloo.ca/mailman/listinfo/wics-volunteers). The only exception is volunteering
this line should be only 80 characters.

Also can you mention that wics-sys isn't taking volunteers now?

2017-01-31 02:54 UTC, annalorimer commented
No extra commits! Awesome job 😄

2017-01-31 03:34 UTC, mokaixu commented on content/pages/volunteers.md
> +form](https://lists.uwaterloo.ca/mailman/listinfo/wics-volunteers). The only exception is volunteering
I will do that rn!

2017-02-02 17:42 UTC, annalorimer commented
This pr references #249

2017-02-03 00:12 UTC, evykassirer commented on content/pages/volunteers.md
> +technical concepts to others. We will no longer be accepting volunteers
mmm sounds a little blunt, and not enough context I think?

"We currently don't have capacity to support volunteers for our systems committee, and will not be accepting systems committee volunteers until further notice."

(something like that, doesn't have to be that)

2017-02-03 00:13 UTC, evykassirer commented on content/pages/volunteers.md
> +technical concepts to others. We will no longer be accepting volunteers
there's also a "Systems Committee Volunteer" section on this page you can get rid of for now, or add a note to

2017-02-03 17:52 UTC, annalorimer commented on content/pages/volunteers.md
> +technical concepts to others. We will no longer be accepting volunteers
This should be "Currently we are not accepting new volunteers  ... ". We will be reinstating the volunteer program as soon as we have mentors available. 

This note should also go at the top of the page. No point having it be buried this deep.

2017-02-03 17:52 UTC, annalorimer commented on content/pages/volunteers.md
> +form](https://lists.uwaterloo.ca/mailman/listinfo/wics-volunteers).**
General question: I agree that we need to update the link, but if we aren't currently taking volunteers should they be able to subscribe to the list? I guess people can sign up and wait until the program gets rebooted.

2017-02-03 18:01 UTC, evykassirer commented on content/pages/volunteers.md
> +form](https://lists.uwaterloo.ca/mailman/listinfo/wics-volunteers).**
yeah that's what I was thinking

2017-02-06 15:48 UTC, evykassirer commented on content/pages/volunteers.md
> +**Note:** We currently don't have the capacity to support volunteers and will
we're still accepting volunteers, just not systems committee volunteers - right?

2017-02-08 14:10 UTC, annalorimer requested changes

2017-02-08 14:10 UTC, annalorimer commented on content/pages/volunteers.md
> +**Note:** We currently don't have the capacity to support volunteers and will
I was under the impression that we would continue to accept people on to the volunteer mailing list, but make it clear that we don't currently have the infrastructure to support the volunteer program.

2017-02-08 14:10 UTC, annalorimer commented on content/pages/volunteers.md
> -### Systems Committee Volunteer
I think this can stay up on the site, just make it clear we aren't accepting people for the roles.

2017-02-08 14:10 UTC, annalorimer commented on content/pages/volunteers.md
>  ### Run an event with us!
Maybe we should move this up to the top of the page? Currently this is the only volunteer "position" we can support.

2017-02-08 14:10 UTC, annalorimer commented on content/pages/volunteers.md
> +**Note:** We currently don't have the capacity to support volunteers and will
Move this to the top of the page?

2017-02-18 06:36 UTC, fat1996 commented
@mokaixu Could you please make the requested changes at your earliest convenience?

2017-02-19 13:08 UTC, mokaixu commented
Made the changes :D sorry for the delay

2017-02-19 14:28 UTC, annalorimer approved these changes

2017-02-19 14:28 UTC, merged