Made event post for techtalk with Monica Beckwith
wics-uw/website pull request #303
Opened 2017-02-04 00:17 UTC by fat1996

Suggestions on what to add for event description? Or this this enough?

2017-02-04 03:18 UTC, evykassirer commented
please use the abstract Monica emailed us. this should be on all advertising for the talk

2017-02-08 16:45 UTC, annalorimer requested changes

2017-02-08 16:45 UTC, annalorimer commented on content/W2017/W17-event-Techtalk-with-Monica-Bechwith.md
> +Slug: tech-talk-w17
This slug need to be more descriptive.

2017-02-08 16:45 UTC, annalorimer commented on content/W2017/W17-event-Techtalk-with-Monica-Bechwith.md
> +Come learn about JIT, Runtime Optimizations, and HotSpot garbage collection with Monica Beckwith!
Use the talk abstract here.

2017-02-08 16:45 UTC, annalorimer commented on content/W2017/W17-event-Techtalk-with-Monica-Bechwith.md
> ++ **Who:** Monica Beckwith
This should detail who is permitted to attend the event, in this case everyone 😊

2017-02-08 16:45 UTC, annalorimer commented on content/W2017/W17-event-Techtalk-with-Monica-Bechwith.md
> +Tags: social
I think there's a 'talks' tag that should be added.

2017-02-11 04:56 UTC, closed without merging