Oh description
wics-uw/website pull request #307
Opened 2017-02-08 22:33 UTC by esedward

Added office hour description to office hour page

2017-02-08 22:35 UTC, evykassirer commented on content/W2017/W17-Office-Hours.md
> +Office Location:
if you want separate lines, add an extra new line between

otherwise you can put this both on the same line

2017-02-08 22:35 UTC, evykassirer commented on content/pages/contact.md
> +[here]({filename}/W2017/W17-Office-Hours.md).
this was already merged hmm, you should merge master into your current branch so this change isn't in this pull request

2017-02-09 17:30 UTC, annalorimer requested changes

2017-02-09 17:30 UTC, annalorimer commented on content/W2017/W17-Office-Hours.md
> +- Candy. You can have some :)
Mention that it's free :)

2017-02-09 17:30 UTC, annalorimer commented on content/W2017/W17-Office-Hours.md
> +- Meet the execs, learn about becoming an exec in the future
'execs' should be 'committee member'

2017-02-09 17:30 UTC, annalorimer commented on content/W2017/W17-Office-Hours.md
> +When you visit us, keep in mind our [office policy]({filename}/pages/code-of-contact.md).
This is already stated below.

2017-02-09 17:30 UTC, annalorimer commented on content/W2017/W17-Office-Hours.md
> +**Come talk to us about:**
Maybe bold 'Why should you come to WiCS office hours?' instead.

2017-02-09 17:30 UTC, annalorimer commented on content/W2017/W17-Office-Hours.md
>  - 11 am - 1 pm
The dashes aren't rendering as bullet points. I think the problem is that you used '+' for the days of the week and dashes for the times?

2017-02-09 17:31 UTC, evykassirer commented on content/W2017/W17-Office-Hours.md
>  - 11 am - 1 pm
it's the same problem with needing a newline before a list I think

2017-02-09 17:32 UTC, annalorimer commented on content/W2017/W17-Office-Hours.md
>  - 11 am - 1 pm
Markdown is hard 😢

2017-02-10 20:35 UTC, esedward commented
Ok so all the comments/changes you guys mentioned, did you change them already or do I need to go back and fix things? @evykassirer @annalorimer

2017-02-10 20:37 UTC, evykassirer commented
you fix 'em and then commit in the same branch and push again and they'll show up here :)

2017-02-14 22:05 UTC, esedward commented on content/W2017/W17-Office-Hours.md
> +When you visit us, keep in mind our [office policy]({filename}/pages/code-of-contact.md).
where? I don't see it

2017-02-16 00:52 UTC, fat1996 commented
@annalorimer @evykassirer can this be closed?

2017-02-16 01:03 UTC, fat1996 requested changes
@esedward is "The Code of Conduct is in effect at all times during office hours." supposed to be bold? It's showing up with an extra pair of *'s. You can view it here: https://wics-site-pr-307.herokuapp.com/2017/01/office-hours-for-winter-2017/

2017-02-16 01:12 UTC, esedward commented
@fat1996 yes I meant it to be bold I think I need to take out a few * and add a newline I'll fix that right now

2017-02-16 01:19 UTC, esedward commented
@fat1996 done?

2017-02-16 01:27 UTC, fat1996 approved these changes
@esedward looks good!(the last 2 lines are in italics now, instead of bold).

2017-02-16 01:29 UTC, esedward commented
@fat1996 italics are fine

2017-02-16 02:14 UTC, annalorimer commented on content/pages/contact.md
> +[here]({filename}/F2016/F16-Office-Hours.md).
Are these supposed to be the F16 hours?

2017-02-18 06:37 UTC, fat1996 commented
@esedward Could you please make the requested change at your earliest convenience? I wanna close this PR.

2017-03-01 03:13 UTC, esedward commented
I'm sorry I don't understand what I need to do. I thought I changed the link to W17 in another PR

2017-03-01 15:32 UTC, evykassirer commented
I think you did - so the main copy of the site has it as W17, but this PR seems to be changing it back. If you change it in your version to W17, it won't show up in the diff at all

let me know if that makes sense, if you have questions, etc!

2017-03-01 18:05 UTC, esedward commented
@fat1996 I think I fixed it

2017-03-01 19:02 UTC, fat1996 commented
@annalorimer @evykassirer what could cause a failure to deploy^? also, can these changes be approved?

2017-03-01 20:01 UTC, evykassirer commented
these are the logs, i'm not sure why it's failing - can you investigate?

```
-----> Pelican app detected
-----> Installing Python (python-3.4.3)
-----> Ensure pip
       Ignoring indexes: https://pypi.python.org/simple
       Collecting setuptools
       Collecting pip
       Installing collected packages: pip, setuptools
       
       
       Successfully installed pip-6.0.8 setuptools-12.0.5
-----> Installing Pelican
       You are using pip version 6.0.8, however version 9.0.1 is available.
       You should consider upgrading via the 'pip install --upgrade pip' command.
-----> Installing Markdown
       You are using pip version 6.0.8, however version 9.0.1 is available.
       You should consider upgrading via the 'pip install --upgrade pip' command.
-----> Downloading binary files
--2017-03-01 19:59:57--  https://github.com/wics-uw/website-binary/archive/master.zip
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/wics-uw/website-binary/zip/master [following]
--2017-03-01 19:59:57--  https://codeload.github.com/wics-uw/website-binary/zip/master
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘master.zip’
     0K .......... .......... .......... .......... .......... 18.0M
    50K .......... .......... .......... .......... .......... 10.9M
   100K .......... .......... .......... .......... .......... 52.8M
   150K .......... .......... .......... .......... .......... 10.2M
   200K .......... .......... .......... .......... .......... 11.7M
   250K .......... .......... .......... .......... .......... 16.8M
   300K .......... .......... .......... .......... .......... 49.7M
   350K .......... .......... .......... .......... .......... 43.7M
   400K .......... .......... .......... .......... .......... 40.7M
   450K .......... .......... .......... .......... .......... 11.2M
   500K .......... .......... .......... .......... .......... 12.0M
   550K .......... .......... .......... .......... .......... 11.8M
   600K .......... .......... .......... .......... .......... 22.2M
   650K .......... .......... .......... .......... .......... 12.8M
   700K .......... .......... .......... .......... .......... 28.5M
   750K .......... .......... .......... .......... .......... 13.6M
   800K .......... .......... .......... .......... .......... 12.9M
   850K .......... .......... .......... .......... .......... 12.4M
   900K .......... .......... .......... .......... .......... 41.4M
   950K .......... .......... .......... .......... .......... 23.8M
  1000K .......... .......... .......... .......... .......... 22.1M
  1050K .......... .......... .......... .......... .......... 9.87M
  1100K .......... .......... .......... .......... .......... 15.1M
  1150K .......... .......... .......... .......... .......... 42.6M
  1200K .......... .......... .......... .......... .......... 13.7M
  1250K .......... .......... .......... .......... .......... 19.4M
  1300K .......... .......... .......... .......... .......... 49.4M
  1350K .......... .......... .......... .......... .......... 14.7M
  1400K .......... .......... .......... .......... .......... 32.7M
  1450K .......... .......... .......... .......... .......... 50.6M
  1500K .......... .......... .......... .......... ..........  134M
  1550K .......... .......... .......... .......... .......... 78.0M
  1600K .......... .......... .......... .......... .......... 38.6M
  1650K .......... .......... .......... .......... .......... 52.8M
  1700K .......... .......... .......... .......... .......... 48.6M
  1750K .......... .......... .......... .......... .......... 36.4M
  1800K .......... .......... .......... .......... .......... 15.1M
  1850K .......... .......... .......... .......... .......... 16.9M
  1900K .......... .......... .......... .......... .......... 14.2M
  1950K .......... .......... .......... .......... .......... 16.6M
  2000K .......... .......... .......... .......... .......... 11.1M
  2050K .......... .......... .......... .......... .......... 20.2M
  2100K .......... .......... .......... .......... .......... 9.77M
  2150K .......... .......... .......... .......... .......... 15.5M
  2200K .......... .......... .......... .......... .......... 17.2M
  2250K .......... .......... .......... .......... .......... 20.3M
  2300K .......... .......... .......... .......... .......... 47.1M
  2350K .......... .......... .......... .......... .......... 51.1M
  2400K .......... .......... .......... .......... .......... 47.6M
  2450K .......... .......... .......... .......... .......... 65.1M
  2500K .......... .......... .......... .......... ..........  146M
  2550K .......... .......... .......... .......... .......... 58.4M
  2600K .......... .......... .......... .......... .......... 42.6M
  2650K .......... .......... .......... .......... .......... 46.7M
  2700K .......... .......... .......... .......... .......... 39.6M
  2750K .......... .......... .......... .......... .......... 14.9M
  2800K .......... .......... .......... .......... .......... 12.9M
  2850K .......... .......... .......... .......... .......... 14.2M
  2900K .......... .......... .......... .......... .......... 12.1M
  2950K .......... .......... .......... .......... .......... 16.9M
  3000K .......... .......... .......... .......... .......... 22.8M
  3050K .......... .......... .......... .......... ..........  127M
  3100K .......... .......... .......... .......... ..........  114M
  3150K .......... .......... .......... .......... ..........  103M
  3200K .......... .......... .......... .......... ..........  115M
  3250K .......... .......... .......... .......... ..........  179M
  3300K .......... .......... .......... .......... ..........  131M
  3350K .......... .......... .......... .......... ..........  104M
  3400K .......... .......... .......... .......... .......... 79.8M
  3450K .......... .......... .......... .......... ..........  105M
  3500K .......... .......... .......... .......... ..........  239M
  3550K .......... .......... .......... .......... ..........  180M
  3600K .......... .......... .......... .......... ..........  116M
  3650K .......... .......... .......... .......... ..........  113M
  3700K .......... .......... .......... .......... ..........  105M
  3750K .......... .......... .......... .......... ..........  112M
  3800K .......... .......... .......... .......... ..........  139M
  3850K .......... .......... .......... .......... ..........  226M
  3900K .......... .......... .......... .......... .......... 22.1M
  3950K .......... .......... .......... .......... .......... 13.8M
  4000K .......... .......... .......... .......... .......... 14.4M
  4050K .......... .......... .......... .......... ..........  289K
  4100K .......... .......... .......... .......... .......... 10.7M
  4150K .......... .......... .......... .......... .......... 8.45M
  4200K .......... .......... .......... .......... .......... 10.2M
  4250K .......... .......... .......... .......... .......... 9.00M
  4300K .......... .......... .......... .......... .......... 7.89M
  4350K .......... .......... .......... .......... .......... 13.3M
  4400K .......... .......... .......... .......... .......... 24.7M
  4450K .......... .......... .......... .......... .......... 11.0M
  4500K .......... .......... .......... .......... .......... 9.42M
  4550K .......... .......... .......... .......... .......... 10.6M
  4600K .......... .......... .......... .......... .......... 9.86M
  4650K .......... .......... .......... .......... [...]

2017-03-01 21:17 UTC, annalorimer commented
@fat1996 It's not immediately obvious what happened. The warning is a known issue.

2017-03-06 14:39 UTC, fat1996 commented
@evykassirer @annalorimer it seems like it couldn't find a URL(/pages/calendar.md). is that it or am I missing something?

2017-03-06 15:24 UTC, annalorimer commented
@fat1996 That's a known issue that's been around for a while. Unless something else changed it shouldn't stop pelican from compiling.

2017-03-14 16:09 UTC, merged