Made event post for techtalk with Monica Beckwith
wics-uw/website pull request #309
Opened 2017-02-11 05:07 UTC by fat1996

2017-02-11 06:28 UTC, evykassirer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> ++Title: Techtalk with Monica Beckwith
it's not showing up on the test site because of these `+`s at the start of your lines

2017-02-11 07:26 UTC, fat1996 commented
Removed the extra +'s.

2017-02-11 07:26 UTC, fat1996 commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> ++Title: Techtalk with Monica Beckwith
Removed the extra +'s.

2017-02-11 17:25 UTC, evykassirer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> +Title: Techtalk with Monica Beckwith
I think it should be two words "tech talk"

2017-02-11 17:26 UTC, evykassirer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> +Monica Beckwith has worked with the Java Virtual Machine for more than a decade not just optimizing the JVM heuristics, but also improving the Just-in-time(JIT) code quality for various processor arc
lines should be max 80 characters

2017-02-11 17:26 UTC, evykassirer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> ++ **Who:** This is a women-only event.
it's open to everyone!

2017-02-11 17:27 UTC, annalorimer requested changes

2017-02-11 17:27 UTC, annalorimer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> +Summary: Come join us at a tech talk with Monica Beckwith!
Maybe something like "Monica Beckwith will be visiting campus to give a talk on her work in ...". You can have a look at https://github.com/wics-uw/website/blob/master/content/W2015/W15-event-hypatia.md for inspiration.

2017-02-11 17:27 UTC, annalorimer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> +Monica Beckwith has worked with the Java Virtual Machine for more than a decade not just optimizing the JVM heuristics, but also improving the Just-in-time(JIT) code quality for various processor arc
80 chars per line.

2017-02-11 17:27 UTC, annalorimer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> +During this talk, Monica will cover a few JIT and Runtime optimizations and she will dive into the HotSpot garbage collection and provide an overview of the various garbage collectors available in Ho
80 chars per line.

2017-02-11 17:27 UTC, annalorimer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> ++ **Who:** This is a women-only event.
Need to link to FAQ.

2017-02-11 17:27 UTC, annalorimer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> ++ **When:** Tuesday March 14, 6:00-7.30pm
7.30pm -> 7:30pm

2017-02-11 17:27 UTC, annalorimer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> ++ **What:** Come join us for a talk with Monica Beckwith
This should be the name of the talk

2017-02-11 17:27 UTC, annalorimer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> +Slug: tech-talk-with-Monica-Beckwith-w17
This is a little long now 😛

2017-02-11 17:27 UTC, annalorimer commented on content/W2017/W17-event-techtalk-with-Monica-Beckwith.md
> +Title: Techtalk with Monica Beckwith
Techtalk -> Tech Talk

2017-02-12 17:06 UTC, evykassirer approved these changes

2017-02-12 23:37 UTC, merged