created event post for ctf workshop W17
wics-uw/website pull request #310
Opened 2017-02-11 05:38 UTC by fat1996

2017-02-11 17:38 UTC, annalorimer requested changes
Sorry I know I told you to just copy the last one ...

2017-02-11 17:38 UTC, annalorimer commented on content/W2017/W17-event-ctf.md
> +title: Security and Networking CTF
we should add "with CrySP" since we're collaborating. (I know I told you to just copy the last one sorry 😛)

2017-02-11 17:38 UTC, annalorimer commented on content/W2017/W17-event-ctf.md
> +start?
If you want a line between paragraphs you'll need an extra line here.

2017-02-11 17:38 UTC, annalorimer commented on content/W2017/W17-event-ctf.md
> +Undergrad's Security and Networking CTF (Capture the Flag)! There will be
add something like "hosted in collaboration with CrySP" and link to the lab https://crysp.uwaterloo.ca/

2017-02-11 17:38 UTC, annalorimer commented on content/W2017/W17-event-ctf.md
> ++ **Where:** TBD
EV3 1408 has been booked.

2017-02-13 14:41 UTC, annalorimer requested changes
These should be the last changes I promise :)

2017-02-13 14:41 UTC, annalorimer commented on content/W2017/W17-event-ctf.md
>  Date: TBD
Date is Feb 28th.

2017-02-13 14:41 UTC, annalorimer commented on content/W2017/W17-event-ctf.md
> +and competition and questions about security, crypto, networking and
"This is a team competition with questions about security, crypto, networking and infrastructure! There will also be snacks and prizes!

2017-02-15 18:16 UTC, annalorimer commented
@fat1996 can you get these changes in asap? We should have all the advertising stuff finished by friday.

2017-02-15 18:50 UTC, fat1996 commented
@annalorimer Made the changes.

2017-02-15 18:56 UTC, annalorimer requested changes

2017-02-15 18:56 UTC, annalorimer commented on content/W2017/W17-event-ctf.md
> +Date: Feb 28th, 2017
This needs to be formatted as 2017-02-28 for the website to parse it properly.

2017-02-15 20:44 UTC, annalorimer approved these changes

2017-02-15 20:44 UTC, merged