removed tags that've only been used once
wics-uw/website pull request #313
Opened 2017-02-18 21:09 UTC by fat1996

2017-02-18 22:13 UTC, annalorimer requested changes

2017-02-18 22:13 UTC, annalorimer commented on content/S2015/S15-event-alterconf.md
> +Tags:
The conference tag should be kept here.

2017-02-18 22:13 UTC, annalorimer commented on content/S2016/S16-event-square.md
> +Tags: workshop, open source
Keep the square tag.

2017-02-18 22:13 UTC, annalorimer commented on content/W2016/W16-event-big-data-panel.md
> +Tags: panels
I think we should keep tags like 'big data' and 'graphics'. Makes it easy to search for events imo.

2017-02-18 22:13 UTC, annalorimer commented on content/W2016/W16-event-problem-solving-session.md
> +Tags:
This should probably have the Big CSters tag.

2017-02-18 22:15 UTC, evykassirer commented on content/S2016/S16-event-square.md
> +Tags: workshop, open source
do we want a tag for every company?

2017-02-18 22:17 UTC, annalorimer commented on content/S2016/S16-event-square.md
> +Tags: workshop, open source
Not sure. But there's only two right now so it's not too bad to keep them.

2017-02-26 05:13 UTC, fat1996 commented
@evykassirer @annalorimer could I get any feedback on this? I wanna close this before the end of this week.

2017-02-26 05:15 UTC, evykassirer commented on content/S2016/S16-event-csters-technical-speaking.md
> ++ **When:** Monday June 27, 6:00 - 8:00 PM
may as well change this to ndash

2017-02-26 05:15 UTC, evykassirer commented
👍

2017-02-26 16:21 UTC, annalorimer reviewed
Just the one question but other than that lgtm.

2017-02-26 16:21 UTC, annalorimer commented on content/S2016/S16-event-csters-technical-speaking.md
> +- **When:** Monday June 27, 6:00 - 8:00 PM
Why does this changed to a '-'?

2017-02-27 17:07 UTC, fat1996 commented
@annalorimer I misunderstood where the ndash was supposed to go. is this okay?

2017-02-27 17:10 UTC, annalorimer commented on content/S2016/S16-event-csters-technical-speaking.md
> ++ **When:** Monday June 27, 6:00&ndash;8:00 PM
There should only be one '+' :)

2017-02-27 17:26 UTC, fat1996 commented on content/S2016/S16-event-csters-technical-speaking.md
> ++ **When:** Monday June 27, 6:00&ndash;8:00 PM
@annalorimer i only see 1 '+' in my repo

2017-02-27 17:33 UTC, annalorimer commented on content/S2016/S16-event-csters-technical-speaking.md
> ++ **When:** Monday June 27, 6:00&ndash;8:00 PM
Yup you're right.

2017-02-27 17:34 UTC, annalorimer approved these changes

2017-03-01 19:03 UTC, fat1996 commented
@annalorimer @evykassirer can this be merged?

2017-03-01 21:17 UTC, merged