Made event post for DDOW
wics-uw/website pull request #315
Opened 2017-02-24 04:45 UTC by fat1996

2017-02-24 14:22 UTC, annalorimer requested changes

2017-02-24 14:22 UTC, annalorimer commented on content/W2017/W17-blog-DDOW.md
> + +overlooked and undervalued. WiCS thanks everyone who participated in
WiCS thanks -> WiCS stands with

2017-02-24 14:22 UTC, annalorimer commented on content/W2017/W17-blog-DDOW.md
> + +Summary: WiCS thanks everyone who participated in the Distributed Denial of Women on Feb 23rd, 2017!
WiCS thanks -> WiCS stands with

Remove the exclamation points too.

2017-02-24 14:22 UTC, annalorimer commented on content/W2017/W17-blog-DDOW.md
> + +the [Distributed Denial of Women](http://distributed-denial-of-women.org/) on February 23rd, 2017
lines need to be 80 char 😊

2017-02-24 14:22 UTC, annalorimer commented on content/W2017/W17-blog-DDOW.md
> + +and stood up for women and non-binary people, who are essential to tech.
women -> cis and trans women

2017-02-24 21:33 UTC, annalorimer commented
@fat1996 ping!

2017-02-24 22:52 UTC, fat1996 commented
@annalorimer should I replace all mentions of women with cis and trans women? I wasn't sure which one you were referring to.

2017-02-25 01:21 UTC, annalorimer commented
@fat1996 good question. @evykassirer might have a better way of saying something like 'gender minorities' but better worded.

2017-02-25 01:42 UTC, fat1996 commented
@evykassirer could you give me some suggestions as to how to reword it? replace 'women' with 'cis and trans women, non binary individuals and other gender minorities'?

2017-02-25 02:12 UTC, evykassirer commented
hmm I think "gender minorities" is concise but not very specific (we generally don't include trans men, for example)

I think we should stick with what we always say and do "cis and trans women, and non-binary individuals"

2017-02-26 04:57 UTC, bdamerac commented
There's still the exclamation. Otherwise, looks good to me.

2017-02-26 16:13 UTC, annalorimer commented
There shouldn't be any '+' before the fields at the top of the file. I'll remove these and merge.

2017-02-26 16:14 UTC, merged