Add WiCS/WiM Dinner with the Professors event post
wics-uw/website pull request #316
Opened 2017-03-02 03:27 UTC by taliamccormick

2017-03-02 14:34 UTC, annalorimer requested changes

2017-03-02 14:34 UTC, annalorimer commented on content/W2017/W17-event-dinner-with-professors.md
> +Come have dinner with the brilliant women who are professors at Waterloo! This is a wonderful opportunity to learn about their research, academia, teaching, and your own academic interests.
Lines need to be 80 char long.

2017-03-02 14:34 UTC, annalorimer commented on content/W2017/W17-event-dinner-with-professors.md
> ++ **Note:** Tickets for students are sold for $10 in MathSoc, until Wednesday, March 1. Sign-up for professors and for grad students who are interested in attending as mentors is free and run through
This note should go in the main part of the post. The lines also need to be 80 char long. 

The link to the eventbrite should be embedded. i.e [evenbrite](goo.gl/B8PQHL).

2017-03-02 14:34 UTC, annalorimer commented on content/W2017/W17-event-dinner-with-professors.md
> +Summary: Student-faculty dinner.
This should be something like "Join WiCS for our second dinner with profs event!" or something to that effect. i.e more pep

2017-03-02 14:37 UTC, fat1996 requested changes
it would be better to italicize or underline the wics email address.

2017-03-02 17:18 UTC, taliamccormick commented
Looks better?
Should I hyperlink the email address, also?

2017-03-02 17:21 UTC, fat1996 commented
@taliamccormick yeah, I mentioned that in my comments.

2017-03-02 17:48 UTC, annalorimer requested changes

2017-03-02 17:48 UTC, annalorimer commented on content/W2017/W17-event-dinner-with-professors.md
> +is required and is first-come first-serve. If you can   not make it to the
Extra spaces between "can" and "not"

2017-03-02 17:48 UTC, annalorimer commented on content/W2017/W17-event-dinner-with-professors.md
> +1. Registration for professors and for grad students who are interested in
This miiiiiight render as a numbered list. Not sure, heroku is being stupid.

2017-03-02 17:48 UTC, annalorimer commented on content/W2017/W17-event-dinner-with-professors.md
> +find   a workaround.
Extra spaces between "find" and "a"

2017-03-03 03:39 UTC, taliamccormick commented on content/W2017/W17-event-dinner-with-professors.md
> +1. Registration for professors and for grad students who are interested in
It looks fine when I run locally.
![screenshot 2017-03-02 22 36 39](https://cloud.githubusercontent.com/assets/13280845/23537245/c530782a-ff98-11e6-9b21-2741597d128c.png)
Putting the "1." back a line will make the previous line greater than 80 characters wide. I could change it to say "March first" instead. Alternatively, I could move March onto the next line, also.

2017-03-03 13:16 UTC, annalorimer commented on content/W2017/W17-event-dinner-with-professors.md
> +1. Registration for professors and for grad students who are interested in
Perfect.

2017-03-03 13:17 UTC, annalorimer approved these changes

2017-03-03 13:17 UTC, merged