new post about monica's talk on march 14
wics-uw/website pull request #317
Opened 2017-03-05 13:43 UTC by mokaixu

Post for the tech talk as requested :)

2017-03-05 16:26 UTC, evykassirer requested changes
thanks for putting this up! it was on my todo list for this morning but I'm grateful you took it on ❤️ 

overall looks great - left a few comments for changes

2017-03-05 16:26 UTC, evykassirer commented on content/W2017/W17-event-beckwith-talk.md
> +Title: Tech Talk: Hotspot Virtual Machine's Execution Engine by Monica Beckwith
I like the idea of adding out of town, like in http://wics.uwaterloo.ca/2016/02/stephanie-morillo-talk/

`Out of Town Speaker: Hotspot Virtual Machine's Execution Engine by Monica Beckwith`

2017-03-05 16:26 UTC, evykassirer commented on content/W2017/W17-event-beckwith-talk.md
> +Tags: events, academic
'talks'

2017-03-05 16:26 UTC, evykassirer commented on content/W2017/W17-event-beckwith-talk.md
> +Monica Beckwith has worked with the Java Virtual Machine
can you add an intro before this paragraph that looks like the first paragraph in http://wics.uwaterloo.ca/2016/02/stephanie-morillo-talk/ ?

2017-03-05 16:26 UTC, evykassirer commented on content/W2017/W17-event-beckwith-talk.md
> +Summary: Come listen about the amazing work Monica Beckwith is doing!
come listen **to**

2017-03-05 16:26 UTC, evykassirer commented on content/W2017/W17-event-beckwith-talk.md
> +Monica Beckwith has worked with the Java Virtual Machine
and then "Abstract:" before this line

2017-03-06 14:08 UTC, annalorimer requested changes

2017-03-06 14:08 UTC, annalorimer commented on content/W2017/W17-event-beckwith-talk.md
> +Tags: events, academic
Adding on to Evy's comment: 

Replace 'events' with 'talks'.

2017-03-06 14:08 UTC, annalorimer commented on content/W2017/W17-event-beckwith-talk.md
> +Summary: Come listen about the amazing work Monica Beckwith is doing!
The summary is basically like a headline, so we want to include more information about the talk. Have a look at the Leigh Honeywell post, there's a good example there.

2017-03-06 14:08 UTC, annalorimer commented on content/W2017/W17-event-beckwith-talk.md
> +Note: Please claim your free admission ticket [here]
'Please claim your free admission ticket [here]' -> 'Registration is required. Tickets are available [here]"

2017-03-06 14:08 UTC, annalorimer commented on content/W2017/W17-event-beckwith-talk.md
> ++ **What:** Tech Talk
Again, have a look at the Leigh Honeywell post for a good idea of how to use this section 😄

2017-03-06 14:08 UTC, annalorimer commented on content/W2017/W17-event-beckwith-talk.md
> ++ **Where:** Science Teaching Complex 0040
Add STC in brackets after the building name.

2017-03-06 14:26 UTC, annalorimer commented
Actually, @fat1996 already made an event post. I reverted master because we wanted other events to be at the top of the page.

2017-03-06 14:29 UTC, annalorimer commented
Closing this issue since we already have an event post. 

Sorry @mokaixu you went and did all this work 😞.

2017-03-06 14:29 UTC, closed without merging

2017-03-06 18:12 UTC, mokaixu commented
Hi Just saw the requests! No problem @annalorimer It was good practise :)

LOL very efficient now after all that troubleshooting :')