S17 committee apps
wics-uw/website pull request #320
Opened 2017-03-11 18:45 UTC by fat1996

2017-03-11 23:14 UTC, annalorimer requested changes

2017-03-11 23:14 UTC, annalorimer commented on content/W2017/W17-new-committee-applications-S17.md
> +Title: Spring 2017 WiCS Committee Applications
The file name is a lil funky. To change just do "mv <oldfilename> <newfilename>"

2017-03-11 23:14 UTC, annalorimer commented on content/W2017/W17-new-committee-applications-S17.md
> ++ You don't need any prior experience to apply. If you have a desire to improve the social and academic environment of women and non-binary people in computer science, that's exactly what we're looki
Lines should be 80 char.

2017-03-14 16:07 UTC, annalorimer commented
There's two files included in this pr ... You'll need to remove the one with the wrong name.

2017-03-15 02:56 UTC, fat1996 commented
@annalorimer deleted the extra file

2017-03-15 13:01 UTC, annalorimer approved these changes

2017-03-15 13:02 UTC, merged