Add F17 options panel event post
wics-uw/website pull request #337
Opened 2017-11-08 10:56 UTC by RootLuo

@esedward Would you mind taking a look at this pr? Thanks!

2017-11-08 17:10 UTC, annalorimer submitted a review, later dismissed

2017-11-08 17:10 UTC, annalorimer commented on content/F2017/F17-event-options-panel.md
> +Explore exciting options in CS! No idea what courses you want to take? Not sure what to do with your CS passions? Come to our Advisor Panel to find out! Talk to upper years and advisors about the opt
Lines need to be 80chars long.

2017-11-08 18:04 UTC, esedward commented
@RootLuo content looks good but tbh I'm not the best person to ask to review pull requests. You can @ Anna, Evy, Fatema, or Fatima (off the top of my head but there are others) to look them over

2017-11-08 18:29 UTC, mokaixu requested changes

2017-11-08 18:29 UTC, mokaixu commented on content/F2017/F17-event-options-panel.md
> +This is a women-only event.
For consistency ... need the 
Who
What
When 
see http://wics.uwaterloo.ca/2017/03/dinner-with-professors-W17/ for example

dont forget to link the faq for women only

2017-11-10 00:15 UTC, esedward commented
like Monica's example, 

description I gave you

Note: This is a women-only event. (link to faq)

Event Details

* Who: Women and non-binary individuals
* Where: MC 5479
* When: Thursday September 28, 2017, 6 pm - 8 pm
* Cost: Free!

2017-11-17 18:54 UTC, merged